### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by Biaocsu** [1049451037/pytext_clf#1]
@1049451037  你好，我在运行过程中遇到这样的问题，在facebook官方开源git中也没有发现别人遇到过，我仅仅只是数据量比你的大而已，请问你碰到过没有，或知道什么原因吗？不甚感激

(liubiao) kingsoft@ubuntu:~/liubiao/desktop/pytext$ pytext train < config.json
No config file specified, reading from stdin

===Starting training...

Parameters: PyTextConfig:
    task: DocClassificationTask.Config:
        features: ModelInputConfig:
        featurizer: SimpleFeaturizer.Config:
        data_handler: DocClassificationDataHandler.Config:
            columns_to_read: ['text', 'doc_label']
            shuffle: True
            sort_within_batch: True
            train_path: data/dataset/train.tsv
            eval_path: data/dataset/dev.tsv
            test_path: data/dataset/test.tsv
            train_batch_size: 128
            eval_batch_size: 128
            test_batch_size: 128
            max_seq_len: -1
        trainer: Trainer.Config:
            epochs: 15
            early_stop_after: 0
            max_clip_norm: None
            report_train_metrics: True
        optimizer: Adam.Config:
        scheduler: Scheduler.Config:
        exporter: None
        random_seed: 0
        model: DocModel.Config:
            representation: BiLSTMDocAttention.Config:
                load_path: None
                save_path: None
                freeze: False
                shared_module_key: None
                dropout: 0.4
                lstm: BiLSTM.Config:
                pooling: SelfAttention.Config:
                mlp_decoder: None
            decoder: MLPDecoder.Config:
            output_layer: ClassificationOutputLayer.Config:
        labels: DocLabelConfig:
        metric_reporter: ClassificationMetricReporter.Config:
    use_cuda_if_available: True
    distributed_world_size: 1
    load_snapshot_path: 
    save_snapshot_path: /tmp/model.pt
    export_caffe2_path: /tmp/model.caffe2.predictor
    export_onnx_path: /tmp/model.onnx
    modules_save_dir: 
    save_module_checkpoints: False
    use_tensorboard: True
    test_out_path: /tmp/test_out.txt
    debug_path: /tmp/model.debug

    # for debug of GPU
    use_cuda_if_available: True
    device_id: 0
    world_size: 1
    torch.cuda.is_available(): True
    cuda_utils.CUDA_ENABLED: True
    cuda_utils.DISTRIBUTED_WORLD_SIZE: 1
    
Task parameters:

{'data_handler': {'columns_to_read': ['text', 'doc_label'],
                  'eval_batch_size': 128,
                  'eval_path': 'data/dataset/dev.tsv',
                  'max_seq_len': -1,
                  'shuffle': True,
                  'sort_within_batch': True,
                  'test_batch_size': 128,
                  'test_path': 'data/dataset/test.tsv',
                  'train_batch_size': 128,
                  'train_path': 'data/dataset/train.tsv'},
 'exporter': None,
 'features': {'char_feat': None,
              'dense_feat': None,
              'dict_feat': None,
              'freeze': False,
              'load_path': None,
              'pretrained_model_embedding': None,
              'save_path': None,
              'shared_module_key': None,
              'word_feat': {'embed_dim': 100,
                            'embedding_init_range': None,
                            'embedding_init_strategy': 'random',
                            'export_input_names': ['tokens_vals'],
                            'freeze': False,
                            'lowercase_tokens': True,
                            'min_freq': 1,
                            'mlp_layer_dims': [],
                            'pretrained_embeddings_path': '',
                            'vocab_file': '',
                            'vocab_from_all_data': False,
                            'vocab_from_pretrained_embeddings': False,
                            'vocab_from_train_data': True,
                            'vocab_size': 0}},
 'featurizer': {'SimpleFeaturizer': {'convert_to_bytes': False,
                                     'lowercase_tokens': True,
                                     'sentence_markers': None,
                                     'split_regex': '\\s+'}},
 'labels': {'export_output_names': ['doc_scores'],
            'label_weights': {},
            'target_prob': False},
 'metric_reporter': {'model_select_metric': 'accuracy',
                     'output_path': '/tmp/test_out.txt',
                     'target_label': None},
 'model': {'decoder': {'freeze': False,
                       'hidden_dims': [],
                       'load_path': None,
                       'save_path': None,
                       'shared_module_key': None},
           'output_layer': {'freeze': False,
                            'load_path': None,
                            'loss': {'CrossEntropyLoss': {}},
                            'save_path': None,
                            'shared_module_key': None},
           'representation': {'BiLSTMDocAttention': {'dropout': 0.4,
                                                     'freeze': False,
                                                     'load_path': None,
                                                     'lstm': {'bidirectional': True,
                                                              'dropout': 0.4,
                                                              'freeze': False,
                                                              'load_path': None,
                                                              'lstm_dim': 32,
                                                              'num_layers': 1,
                                                              'save_path': None,
                                                              'shared_module_key': None},
                                                     'mlp_decoder': None,
                                                     'pooling': {'SelfAttention': {'attn_dimension': 64,
                                                                                   'dropout': 0.4}},
                                                     'save_path': None,
                                                     'shared_module_key': None}}},
 'optimizer': {'Adam': {'lr': 0.001, 'weight_decay': 1e-05}},
 'random_seed': 0,
 'scheduler': {'T_max': 1000,
               'cooldown': 0,
               'cut_frac': 0.1,
               'eta_min': 0,
               'gamma': 0.1,
               'lm_gradual_unfreezing': True,
               'lm_lr_multiplier': 1.0,
               'lm_use_per_layer_lr': False,
               'non_pretrained_param_groups': 2,
               'patience': 5,
               'ratio': 32,
               'step_size': 30,
               'threshold': 0.0001,
               'threshold_is_absolute': False,
               'type': 'none'},
 'trainer': {'early_stop_after': 0,
             'epochs': 15,
             'max_clip_norm': None,
             'report_train_metrics': True}}
creating field TextFeatureField
creating field DocLabelField

Loading data...
reading data from data/dataset/train.tsv
ignoring line 157
ignoring line 10366
ignoring line 12484
ignoring line 12836
ignoring line 14172
reading data from data/dataset/dev.tsv
reading data from data/dataset/test.tsv
Building vocab for feature word_feat.
Adding tokens from train data to vocab.
word_feat field's vocabulary size is 909661
Building vocab for label doc_label
doc_label field's vocabulary size is 2
load_path is not a config of embedding, skipping
save_path is not a config of embedding, skipping
freeze is not a config of embedding, skipping
shared_module_key is not a config of embedding, skipping
dict_feat is not a config of embedding, skipping
char_feat is not a config of embedding, skipping
pretrained_model_embedding is not a config of embedding, skipping
dense_feat is not a config of embedding, skipping
Rank 0 worker: Starting epoch #1
Learning rate(s): 0.001
Rank 0 worker: Running epoch #1 for Stage.TRAIN
/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/pytext/models/representations/pooling.py:48: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  alphas = self.softmax(alphas)  # (bsz, sent_len)
/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/torch/nn/_reduction.py:16: UserWarning: reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.
  warnings.warn("reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.")
Traceback (most recent call last):
  File "/home/kingsoft/anaconda3/envs/liubiao/bin/pytext", line 11, in <module>
    sys.exit(main())
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/pytext/main.py", line 290, in train
    train_model(config, metric_channels)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/pytext/workflow.py", line 71, in train_model
    trained_model, best_metric = task.train(config, rank, world_size)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/pytext/task/task.py", line 163, in train
    rank=rank,
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/pytext/trainers/trainer.py", line 144, in train
    rank=rank,
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/pytext/trainers/trainer.py", line 212, in _run_epoch
    logits = model(*inputs)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/pytext/models/model.py", line 203, in forward
    input_representation = self.representation(token_emb, *other_input)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/pytext/models/representations/bilstm_doc_attention.py", line 115, in forward
    rep, new_state = self.lstm(embedded_tokens, seq_lengths, states)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/pytext/models/representations/bilstm.py", line 107, in forward
    rep, new_state = self.lstm(rnn_input, states)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kingsoft/anaconda3/envs/liubiao/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 182, in forward
    self.num_layers, self.dropout, self.training, self.bidirectional)
RuntimeError: CUDA out of memory. Tried to allocate 3.90 GiB (GPU 0; 15.90 GiB total capacity; 13.83 GiB already allocated; 529.56 MiB free; 982.23 MiB cached)

机器是：
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P5000        Off  | 00000000:03:00.0 Off |                  Off |
| 28%   44C    P0    38W / 180W |      0MiB / 16276MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by 1049451037** [comment]
```RuntimeError: CUDA out of memory. Tried to allocate 3.90 GiB (GPU 0; 15.90 GiB total capacity; 13.83 GiB already allocated; 529.56 MiB free; 982.23 MiB cached)```

你好，看起来是显卡在运行其他程序，已经占了13G内存，空间不够了

**Comment by Biaocsu** [comment]
@1049451037  你好，我确定没有运行其他程序。pytext这个程序的train、dev、test数据总共加起来还不到200M，所以很奇怪，也不知道配置文件里需要怎样对应修改。

**Comment by 1049451037** [comment]
我找了一下官方文档，应该是GPU的坑：

```
If you are using MacOS or Windows, this likely will not include GPU support by default; if you are using Linux, you should automatically get a version of PyTorch compatible with CUDA 9.0.
```

估计是你的CUDA 10.0跟pytext不兼容？

**Comment by Biaocsu** [comment]
@1049451037  非常感谢你这么认真的指导，谢谢

**Comment by 1049451037** [comment]
不客气
